spring:
  application:
        name: project-managment
  datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/projectmanagment
        username: postgres
        password: 2810
  liquibase:
          change-log: classpath:/db/changelog/changelog-master.xml